// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzVWvpn-lLDJ6s1MAUVyPALVZQ849bEpI',
    appId: '1:617980474897:web:31328f50dc2d9f0cb2a3b0',
    messagingSenderId: '617980474897',
    projectId: 'forknkniverestaurant',
    authDomain: 'forknkniverestaurant.firebaseapp.com',
    storageBucket: 'forknkniverestaurant.firebasestorage.app',
    measurementId: 'G-0EF9TK3WST',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBziHBJ7kX87Ytd2gMaiWLOUcxpE6VD7OQ',
    appId: '1:617980474897:android:dd1e2d097800babcb2a3b0',
    messagingSenderId: '617980474897',
    projectId: 'forknkniverestaurant',
    storageBucket: 'forknkniverestaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDG6VD2GpydX9X8Ur58AEPEBmVQ8ZvgGMY',
    appId: '1:617980474897:ios:2ca65533503d99d8b2a3b0',
    messagingSenderId: '617980474897',
    projectId: 'forknkniverestaurant',
    storageBucket: 'forknkniverestaurant.firebasestorage.app',
    iosBundleId: 'com.example.rms',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDG6VD2GpydX9X8Ur58AEPEBmVQ8ZvgGMY',
    appId: '1:617980474897:ios:2ca65533503d99d8b2a3b0',
    messagingSenderId: '617980474897',
    projectId: 'forknkniverestaurant',
    storageBucket: 'forknkniverestaurant.firebasestorage.app',
    iosBundleId: 'com.example.rms',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzVWvpn-lLDJ6s1MAUVyPALVZQ849bEpI',
    appId: '1:617980474897:web:0ef3a1ef4687275db2a3b0',
    messagingSenderId: '617980474897',
    projectId: 'forknkniverestaurant',
    authDomain: 'forknkniverestaurant.firebaseapp.com',
    storageBucket: 'forknkniverestaurant.firebasestorage.app',
    measurementId: 'G-2EE7GD225C',
  );
}
