name: Flutter Android/Web CI

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version: 3.27.1

      - name: Get Dependencies
        run: flutter pub get
      
      - name: Build Android
        run: flutter build apk --debug

      # - name: Build Android Bundle
      #   run: flutter build appbundle

      # - name: Build Web
      #   run: flutter build web --release --web-renderer html

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: app-release
          path: build/app/outputs/flutter-apk/app-debug.apk
        
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: build/app/outputs/flutter-apk/app-debug.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}